<?php

return [
    'available_permissions' => [
        'stores' => ['view', 'create', 'update', 'delete'],
        'store_user_mappings' => ['view', 'create', 'update', 'delete'],
        // 'store_user_module_mappings' => ['view', 'create', 'update', 'delete'],
        'store_kyc_mappings' => ['view', 'create', 'update', 'delete'],
        'products' => ['view', 'create', 'update', 'delete'],
        'product_mappings' => ['view', 'create', 'update', 'delete'],
        'promotion_products' => ['view', 'create', 'update', 'delete'],
        'promotion_product_mappings' => ['view', 'create', 'update', 'delete'],
        'category_trackings' => ['view', 'create', 'update', 'delete'],
        'category_tracking_products' => ['view', 'create', 'update', 'delete'],
        'category_tracking_target_mappings' => ['view', 'create', 'update', 'delete'],
        'competition_products' => ['view', 'create', 'update', 'delete'],
        'competition_product_mappings' => ['view', 'create', 'update', 'delete'],
        'sale_targets' => ['view', 'create', 'update', 'delete'],
        'posms' => ['view', 'create', 'update', 'delete'],
        'posm_store_mappings' => ['view', 'create', 'update', 'delete'],
        'posm_product_mappings' => ['view', 'create', 'update', 'delete'],
        'countries' => ['view', 'create', 'update', 'delete'],
        'states' => ['view', 'create', 'update', 'delete'],
        'cities' => ['view', 'create', 'update', 'delete'],
        'pin_codes' => ['view', 'create', 'update', 'delete'],
        'clients' => ['view', 'create', 'update', 'delete'],
        'promoters' => ['view', 'create', 'update', 'delete'],
        'staff' => ['view', 'create', 'update', 'delete'],
        'staff_hierarchy' => ['view'],
        // 'sub_admins' => ['view', 'create', 'update', 'delete'],
        'roles' => ['view', 'create', 'update', 'delete'],
        'login_requests' => ['view'],
        'leaves' => ['view', 'create', 'audit'],
        'kyc_reports' => ['view', 'audit'],
        'sale_reports' => ['view'],
        'visibility_reports' => ['view', 'audit'],
        'category_tracking_reports' => ['view'],
        'promotion_tracking_reports' => ['view'],
        'competition_benchmarking_reports' => ['view'],
        'types' => ['view', 'create', 'update', 'delete'],
        'chains' => ['view', 'create', 'update', 'delete'],
        'categories' => ['view', 'create', 'update', 'delete'],
        'regions' => ['view', 'create', 'update', 'delete'],
        'formats' => ['view', 'create', 'update', 'delete'],
        'brands' => ['view', 'create', 'update', 'delete'],
        'banners' => ['view', 'create', 'update', 'delete'],
        'store_attendances' => ['view', 'create', 'update', 'delete'],
        'staff_attendances' => ['view', 'create', 'update', 'delete'],
        'reasons' => ['view', 'create', 'update', 'delete'],
        'questions' => ['view', 'create', 'update', 'delete'],
        'services' => ['view', 'create', 'update', 'delete'],
        'payout_clients' => ['view', 'update'],
        'payout_stores' => ['view', 'create'],
        'login_report' => ['view'],
        'system_settings' => ['view', 'update'],
    ],
    'default_permissions' => [
        'stores' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'store_user_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        // 'store_user_module_mappings' => [
        //     'view' => true,
        //     'create' => true,
        //     'update' => true,
        //     'delete' => false,
        // ],
        'store_kyc_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'products' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'product_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'promotion_products' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'promotion_product_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'category_trackings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'category_tracking_products' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'category_tracking_target_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'competition_products' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'competition_product_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'sale_targets' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'posms' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'posm_store_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'posm_product_mappings' => [
            'view' => true,
            'create' => true,
            'update' => true,
            'delete' => false,
        ],
        'countries' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'states' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'cities' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'pin_codes' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'clients' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'promoters' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'staff' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'staff_hierarchy' => [
            'view' => false,
        ],
        // 'sub_admins' => [
        //     'view' => true,
        //     'create' => false,
        //     'update' => false,
        //     'delete' => false,
        // ],
        'roles' => [
            'view' => false,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'login_requests' => [
            'view' => false,
        ],
        'leaves' => [
            'view' => true,
            'create' => true,
            'audit' => false,
        ],
        'kyc_reports' => [
            'view' => true,
            'audit' => false,
        ],
        'sale_reports' => [
            'view' => false,
        ],
        'visibility_reports' => [
            'view' => false,
            'audit' => false,
        ],
        'category_tracking_reports' => [
            'view' => false,
        ],
        'promotion_tracking_reports' => [
            'view' => false,
        ],
        'competition_benchmarking_reports' => [
            'view' => false,
        ],
        'types' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'chains' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'categories' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'regions' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'formats' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'brands' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'banners' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'store_attendances' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'staff_attendances' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'reasons' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'questions' => [
            'view' => true,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'services' => [
            'view' => false,
            'create' => false,
            'update' => false,
            'delete' => false,
        ],
        'payout_clients' => [
            'view' => false,
            'update' => false,
        ],
        'payout_stores' => [
            'view' => false,
            'create' => false,
        ],
        'login_report' => [
            'view' => false,
        ],
        'system_settings' => [
            'view' => false,
            'update' => false,
        ],
    ],
    'permissions_names' => [
        'stores' => 'Stores',
        'store_user_mappings' => 'Store User Mapping',
        // 'store_user_module_mappings' => 'Store User Module Mappings',
        'store_kyc_mappings' => 'Store KYC Mappings',
        'products' => 'Products',
        'product_mappings' => 'Product Mappings',
        'promotion_products' => 'Promotion Products',
        'promotion_product_mappings' => 'Promotion Product Mappings',
        'category_trackings' => 'Category Trackings',
        'category_tracking_products' => 'Category Tracking Products',
        'category_tracking_target_mappings' => 'Category Tracking Target Mappings',
        'competition_products' => 'Competition Products',
        'competition_product_mappings' => 'Competition Product Mappings',
        'sale_targets' => 'Sale Targets',
        'posms' => 'Posms',
        'posm_store_mappings' => 'Posm Store Mappings',
        'posm_product_mappings' => 'Posm Product Mappings',
        'countries' => 'Countries',
        'states' => 'States',
        'cities' => 'Cities',
        'pin_codes' => 'Pinodes',
        'clients' => 'Clients',
        'promoters' => 'Promoters',
        'staff' => 'Staff',
        'staff_hierarchy' => 'Staff Hierarchy',
        // 'sub_admins' => 'Sub Admins',
        'roles' => 'Roles & Permissions',
        'login_requests' => 'Login Auth',
        'leaves' => 'Leaves',
        'kyc_reports' => 'KYC Reports',
        'sale_reports' => 'Sale Reports',
        'visibility_reports' => 'Visibility Reports',
        'category_tracking_reports' => 'Category Tracking Reports',
        'promotion_tracking_reports' => 'Promotion Tracking Reports',
        'competition_benchmarking_reports' => 'Competition Benchmarking Reports',
        'types' => 'Types',
        'chains' => 'Chains',
        'categories' => 'Categories',
        'regions' => 'Regions',
        'formats' => 'Formats',
        'brands' => 'Brands',
        'banners' => 'Banners',
        'store_attendances' => 'Store Attendances',
        'staff_attendances' => 'Staff Attendances',
        'reasons' => 'Reasons',
        'questions' => 'Questions',
        'services' => 'Services',
        'payout_clients' => 'Payout Clients',
        'payout_stores' => 'Payout Stores',
        'login_report' => 'Login Report',
        'system_settings' => 'System Settings',
    ],
    'available_actions' => ['view', 'create', 'update', 'delete', 'audit'],
];
